services:
  - type: web
    name: cards-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: CLIENT_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
